### ISSUE TITLE
Do not allow to pick blocking rocks

### ISSUE THREAD

**Issue by agarzonp** [parmandorc/Descent#16]

**Comment by parmandorc** [comment]
You can solve this by changing the response to the Visibility collision channel to Ignore, in the "RockMesh" MeshComponent of the BlockingRock asset (not individual objects in the scene). That way, the line trace performed by the player will not detect the rocks.

![collision_settings](https://cloud.githubusercontent.com/assets/7033506/21961942/f338067e-db0e-11e6-931f-6bcdc481ecb5.png)
